# Generated by Django 4.0.3 on 2022-03-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='')),
                ('book_description', models.TextField()),
                ('book_price', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('category_id', models.CharField(max_length=100)),
            ],
        ),
    ]
