# Generated by Django 4.0.3 on 2022-03-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_category_remove_books_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
