# Generated by Django 3.0 on 2022-03-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_book_book_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_seller',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='myapp.User'),
        ),
    ]
